---
title: "Day 2 Interactive Lesson"
format: html
editor: visual
execute: 
  echo: true
  warning: false
---

## Making & indexing data in R 

### Vectors

```{r}
dogs <- c("teddy","khora","waffle","banjo","tallie")

#Check the class of dogs
typeof(dogs)
class(dogs)
```

```{r}
my_breakfast <- c("waffles",2,TRUE,"coffee")
typeof(my_breakfast)
```

```{r}
weights <- c(50,60,25,35,55)
typeof(weights)
class(weights)
```

Integer

```{r}
weights_integer <- c(50L, 60L, 25L, 35L, 55L)
typeof(weights_integer)
class(weights_integer)
```

is. function asks a question and then returns TRUE or FALSE

```{r}
is.numeric(weights_integer)
```

Change a class of a variable

```{r}
zipcodes <- c(93105,11220,10009,93101)

#Change from integers to string
#We can use as.__ to reclassify a function

class(zipcodes)

zipcodes_chr <- as.character(zipcodes)
zipcodes_chr
```

## Created a vector with named elements

```{r}
dog_food <- c(teddy = "purina", khora = "alpo", waffle = "fancy feast", banjo = "blue diamond", tallie = "farmer's dog")

dog_food

## The class comes back as what the value is set to here we set it to numbers
test <- c(cat = 4, dog = 10, elephant = 11)
test
class(test)
```

How to return positions of values in vectors

```{r}
# Use brackets [index]
# Values start from 1 and then increase
dog_food[2]

dog_food["teddy"]
```

Access ranges of values in a vector

Use: to refer to a range (low : high)

```{r}
trees <- c("ponderosa","lodgepole", "jeffrey", "sugar","white","bristlecone")

trees[3]

trees[3:5]
```

## Warm up for loops

```{r}
i <- 4
trees[i]
```

Sequence

```{r}
i <- seq(1:3)
trees[i]

yoda <- 4
trees[yoda]
```

```{r}
#Reassign a value in trees  
trees[3] <- "OAK"
trees
```
